
obj-y += part_mxp.o mxp_flash.o
#
#obj-$(CONFIG_MS_SDMMC) += sdmmc/src/hal_card_regs.o sdmmc/src/hal_card_timer.o sdmmc/src/hal_sdmmc.o
#ifeq ($(CONFIG_ARCH_CEDRIC),y)
#obj-$(CONFIG_MS_SDMMC) += sdmmc/src/hal_card_platform_c3.o 
#else ifeq ($(CONFIG_ARCH_CHICAGO),y)
#obj-$(CONFIG_MS_SDMMC) += sdmmc/src/hal_card_platform_c4.o 
#endif
#obj-$(CONFIG_MS_SDMMC) += sdmmc/ms_sdmmc_ub.o 
#obj-$(CONFIG_MS_SDMMC) += sdmmc/ms_sdmmc_drv.o
#obj-$(CONFIG_MS_SDMMC) += sdmmc/ms_sdmmc_verify.o
#
#obj-$(CONFIG_MS_NAND) += unfd/drvNAND.o \
#	unfd/src/api/drvNAND_prg.o \
#	unfd/src/common/drvNAND_hal.o \
#    unfd/src/common/drvNAND_utl.o \
#	unfd/src/config/drvNAND_platform.o
#
	
#obj-$(CONFIG_USB) += usb/usbdcore.o usb/usbtty.o usb/drvusbmain.o usb/drvhostlib.o \
											usb/ehci_usb.o usb/drvusbmain2.o usb/drvhostlib2.o usb/drvusbmain3.o usb/drvhostlib3.o  
#obj-$(CONFIG_ENABLE_USB_LAN_MODULE) += usb/usb_lan.o
#obj-$(CONFIG_ENABLE_USB_LAN_MODULE) += usb/ax88772a.o