#!/bin/sh /etc/rc.common
# Copyright (C) 2011 OpenWrt.org

START=50

USE_PROCD=1
PROG=/usr/sbin/telnetd

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" -F -l /bin/login.sh
	procd_close_instance
}

