module "wt.errcode"

WT_ERRCODE_OK = 0
WT_ERRCODE_PARAMS_INVALID = -1000
WT_ERRCODE_API_TIMEOUT = -1001
WT_ERRCODE_API_INTERNAL = -1002
WT_ERRCODE_MODULE_NOT_FOUND = -1003
WT_ERRCODE_MODULE_API_NOT_FOUND = -1004
WT_ERRCODE_API_FAILED = -1005
WT_ERRCODE_AUTH_FAILED = -1006
WT_ERRCODE_GUIDE_DONE = -1007

WT_ERRCODE_LOGIN_PASSWORD_ERROR = -2000
WT_ERRCODE_ADMIN_PASSWORD_ERROR = -2001

WT_ERRCODE_LOGIN_PASSWORD_ERROR = -2000
WT_ERRCODE_ADMIN_PASSWORD_ERROR = -2001
WT_ERRCODE_SWITCH_INVALID = -2002

WT_ERRCODE_NET_WAN_PROTO_INVALID = -3000
WT_ERRCODE_NET_WAN_LAN_IP_CONFILCT = -3001
WT_ERRCODE_NET_DNS1_INVALID = -3002
WT_ERRCODE_NET_DNS2_INVALID = -3003
WT_ERRCODE_NET_PPPOE_USERNAME_INVALID = -3004
WT_ERRCODE_NET_PPPOE_PASSWORD_INVALID = -3005
WT_ERRCODE_NET_PPPOE_SERVICE_INVALID = -3006
WT_ERRCODE_NET_SSID_INVALID = -3007
WT_ERRCODE_NET_IP_INVALID = -3008
WT_ERRCODE_NET_MASK_INVALID = -3009
WT_ERRCODE_NET_GATEWAY_INVALID = -3010
WT_ERRCODE_NET_DNS_INVALID = -3011
WT_ERRCODE_NET_MTU_INVALID = -3012
WT_ERRCODE_NET_WAN_PHYMODE_INVALID = -3013

WT_ERRCODE_PFORWARD_INSERT_FAILED = -4000
WT_ERRCODE_PFORWARD_INSERT_DUP_FAILED = -4001
WT_ERRCODE_PFORWARD_DELETE_FAILED = -4002
WT_ERRCODE_PFORWARD_MODIFY_FAILED = -4003
WT_ERRCODE_PFORWARD_MODIFY_DUP_FAILED = -4004
WT_ERRCODE_PFORWARD_INSERT_MAXIMUM_EXCEED = -4005
WT_ERRCODE_PFORWARD_IP_NOT_LANNET = -4006
WT_ERRCODE_DMZ_IP_NOT_LANNET = -4007
WT_ERRCODE_PARENT_INSERT_FAILED = -4008
WT_ERRCODE_PARENT_INSERT_DUP_FAILED = -4009
WT_ERRCODE_PARENT_DELETE_FAILED = -4010
WT_ERRCODE_PARENT_MODIFY_FAILED = -4011
WT_ERRCODE_PARENT_MODIFY_DUP_FAILED = -4012
WT_ERRCODE_PARENT_INSERT_MAXIMUM_EXCEED = -4013

WT_ERRCODE_WIRELESS_SSID_INVALID = -5000
WT_ERRCODE_WIRELESS_KEY_INVALID = -5001
WT_ERRCODE_WIRELESS_AUTHMODE_INVALID = -5002
WT_ERRCODE_WIRELESS_CHANNEL_INVALID = -5003
WT_ERRCODE_WIRELESS_HTBW_INVALID = -5004
WT_ERRCODE_WIRELESS_MACFILTER_POLICY_INVALID = -5005
WT_ERRCODE_WIRELESS_MACADDR_ERROR = -5006
WT_ERRCODE_WIRELESS_COMMENT_ERROR = -5007
WT_ERRCODE_WIRELESS_MACFILTER_ACTION_INVALID = -5008
WT_ERRCODE_WIRELESS_MACFILTER_MACADDR_EXIST = -5009
WT_ERRCODE_WIRELESS_MACFILTER_LIST_FULL = -5010
WT_ERRCODE_WIRELESS_MACFILTER_MACADDR_NOTEXIST = -5011
WT_ERRCODE_WIRELESS_MACLIST_EMPTY = -5012

WT_ERRCODE_DHCPS_HOST_NOT_IN_LAN_SUBNET = -6000
WT_ERRCODE_DHCPS_HOST_INSERT_FAILED = -6001
WT_ERRCODE_DHCPS_HOST_INSERT_DUP_FAILED = -6002
WT_ERRCODE_DHCPS_HOST_DELETE_FAILED = -6003
WT_ERRCODE_DHCPS_HOST_MODIFY_FAILED = -6004
WT_ERRCODE_DHCPS_HOST_MODIFY_DUP_FAILED = -6005
WT_ERRCODE_DHCPS_HOST_INSERT_MAXIMUM_EXCEED = -6006

WT_ERRCODE_UPGRADE_FILE_NO_NAME = -7000
WT_ERRCODE_UPGRADE_FILE_TOO_LONG = -7001
WT_ERRCODE_UPGRADE_FILE_PARAM_ERROR = -7002
WT_ERRCODE_UPGRADE_FILE_DATA_ERROR = -7003
WT_ERRCODE_UPGRADE_FILE_IO_FAILED = -7004
WT_ERRCODE_UPGRADE_FILE_FORMAT_ERROR = -7005
WT_ERRCODE_UPGRADE_REMOTE_FAILED = -7006

WT_ERRCODE_DOWNLOAD_FILE_FAILED = -8000
