#!/bin/sh

rmmod kdrv_sdmmc
echo 13 >/sys/class/gpio/export
echo out >/sys/class/gpio/gpio13/direction
echo 1 >/sys/class/gpio/gpio13/value
echo 13 >/sys/class/gpio/unexport
insmod kdrv_sdmmc.ko

insmod esp8089.ko config=crystal_26M_en=1 esp_reset_gpio=13
sleep 1
wifi &
