#!/bin/sh

rmmod kdrv_sdmmc
echo 13 >/sys/class/gpio/export
echo out >/sys/class/gpio/gpio13/direction
echo 1 >/sys/class/gpio/gpio13/value
sleep 1
echo 0 >/sys/class/gpio/gpio13/value
sleep 1
insmod kdrv_sdmmc.ko
sleep 1

insmod esp8089.ko config=crystal_26M_en=1
sleep 1
wifi &
