#
# (C) Copyright 2000-2003
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2008
# Guennadi Liakhovetki, DENX Software Engineering, <lg@denx.de>
#
# SPDX-License-Identifier:	GPL-2.0+
#


obj-y	:= chip.o
obj-$(CONFIG_MS_PIU_TIMER)	+= timer.o
#obj-y	+= ms_serial.o #moved to drivers/sstar/uart
obj-y   += board.o
obj-y   += reset.o
obj-$(CONFIG_SS_BOOTING_PERF)	+= prof.o

