#
# Makefile for MStar IIC HAL drivers.
#


#ifeq ($(MAKE_TYPE), MODULE_STANDALONE)
#include $(TOP_DIR)/modules.mk
#endif


#CONFIG_SSTAR_CHIP_NAME := $(subst ",,$(CONFIG_SSTAR_CHIP_NAME))

# general options
# EXTRA_CFLAGS      +=  -Idrivers/sstar/common
EXTRA_CFLAGS      +=  -Idrivers/sstar/include
EXTRA_CFLAGS      +=  -Idrivers/sstar/i2c
EXTRA_CFLAGS      +=  -Idrivers/sstar/i2c/cedric3

# specific options
#EXTRA_CFLAGS      +=  -Iinclude/asm-mips/titania

# files
#obj-$(CONFIG_MSTAR_IIC)             += mhal_iic.o
